name:                piggy 
version:             1.0.0 
github:              "prosumma/HaskellPG"
license:             MIT
author:              "Gregory Higley"
maintainer:          "greg@prosumma.com"
copyright:           "2022 Gregory Higley" 

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prosumma/HaskellPG#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- exceptions
- free
- listsafe
- mtl
- operational
- postgresql-simple
- string-conversions
- time

library:
  source-dirs: src

executables:
  PG-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piggy 

tests:
  PG-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piggy 
